FormKey: 000807:ScaleTheWorldTheSequel.esm
EditorID: ScaleTheWorldTheSequel_ConfigTerminal
VirtualMachineAdapter:
  Scripts:
  - Name: ScaleTheWorldTheSequel_ConfigTerminalScript
    Properties:
    - MutagenObjectType: ScriptObjectProperty
      Name: ScaleTheWorldTheSequel_ConfigTerminal
      Object: 000805:ScaleTheWorldTheSequel.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: PlayerRef
      Object: 000014:Starfield.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: ScaleTheWorldTheSequel_ConfigTerminal_MainMenu
      Object: 000808:ScaleTheWorldTheSequel.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: ScaleTheWorldTheSequel_EasterEggMode_Critter
      Object: 000844:ScaleTheWorldTheSequel.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: ScaleTheWorldTheSequel_ActivePreset
      Object: 00085B:ScaleTheWorldTheSequel.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: ScaleTheWorldTheSequel_Enabled
      Object: 000806:ScaleTheWorldTheSequel.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: Venpi_DebugEnabled
      Object: 000800:VenpiCore.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: ScaleTheWorldTheSequel_ConfigTerminal_ActivePreset
      Object: 00085C:ScaleTheWorldTheSequel.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: ScaleTheWorldTheSequel_ConfigTerminal_ConfigureEasterEggs
      Object: 000863:ScaleTheWorldTheSequel.esm
Archetype:
  MutagenObjectType: MagicEffectArchetype
  Type: Script
UnkownInt2: 3
CastType: FireAndForget
UnkownInt3: 1065353216
Flags:
- HideInUI
- Painless
- NoHitEffect
Unknown: 0x00000000000000000000000000000000000000000000
