FormKey: 000807:Venworks-ScaleTheWorld.esp
EditorID: VWKS_STW_ConfigTerminal
VirtualMachineAdapter:
  Scripts:
  - Name: VWKS_STW_ConfigTerminalScript
    Properties:
    - MutagenObjectType: ScriptObjectProperty
      Name: VWKS_STW_ConfigTerminal
      Object: 000805:Venworks-ScaleTheWorld.esp
    - MutagenObjectType: ScriptObjectProperty
      Name: PlayerRef
      Object: 000014:Starfield.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: VWKS_STW_ConfigTerminal_MainMenu
      Object: 000808:Venworks-ScaleTheWorld.esp
    - MutagenObjectType: ScriptObjectProperty
      Name: VWKS_STW_EasterEggMode_Critter
      Object: 000844:Venworks-ScaleTheWorld.esp
    - MutagenObjectType: ScriptObjectProperty
      Name: VWKS_STW_ActivePreset
      Object: 000870:Venworks-ScaleTheWorld.esp
    - MutagenObjectType: ScriptObjectProperty
      Name: VWKS_STW_Enabled
      Object: 000806:Venworks-ScaleTheWorld.esp
    - MutagenObjectType: ScriptObjectProperty
      Name: Venpi_DebugEnabled
      Object: 003001:Venworks-ScaleTheWorld.esp
    - MutagenObjectType: ScriptObjectProperty
      Name: VWKS_STW_ConfigTerminal_ActivePreset
      Object: 00085C:Venworks-ScaleTheWorld.esp
    - MutagenObjectType: ScriptObjectProperty
      Name: VWKS_STW_ConfigTerminal_ConfigureEasterEggs
      Object: 000863:Venworks-ScaleTheWorld.esp
    - MutagenObjectType: ScriptStringProperty
      Name: Venpi_ModName
      Data: ScaleTheWorldTheSequel
Archetype:
  MutagenObjectType: MagicEffectArchetype
  Type: Script
UnkownInt2: 3
CastType: FireAndForget
UnkownInt3: 1065353216
Flags:
- HideInUI
- Painless
- NoHitEffect
Unknown: 0x00000000000000000000000000000000000000000000
