FormKey: 000808:Venworks-ScaleTheWorld.esp
EditorID: STWTS_ConfigTerminal_MainMenu
Description:
  TargetLanguage: English
  Value: ''
Name:
  TargetLanguage: English
  Value: NPC Stat Scaler Configuration
Flags:
- MessageBox
BNAM: 4294967295
MenuButtons:
- Text:
    TargetLanguage: English
    Value: Exit
- Text:
    TargetLanguage: English
    Value: Enable NPC Stat Scaling
  Conditions:
  - MutagenObjectType: ConditionFloat
    Unknown1: 0x000000
    Data:
      MutagenObjectType: GetGlobalValueConditionData
      RunOnType: Target
      FirstParameter: 000806:Venworks-ScaleTheWorld.esp
- Text:
    TargetLanguage: English
    Value: Disable NPC Stat Scaling
  Conditions:
  - MutagenObjectType: ConditionFloat
    Unknown1: 0x000000
    Data:
      MutagenObjectType: GetGlobalValueConditionData
      RunOnType: Target
      FirstParameter: 000806:Venworks-ScaleTheWorld.esp
    ComparisonValue: 1
- Text:
    TargetLanguage: English
    Value: Enable Debug Mode
  Conditions:
  - MutagenObjectType: ConditionFloat
    Unknown1: 0x000000
    Data:
      MutagenObjectType: GetGlobalValueConditionData
      FirstParameter: 003001:Venworks-ScaleTheWorld.esp
- Text:
    TargetLanguage: English
    Value: Disable Debug Mode
  Conditions:
  - MutagenObjectType: ConditionFloat
    Unknown1: 0x000000
    Data:
      MutagenObjectType: GetGlobalValueConditionData
      FirstParameter: 003001:Venworks-ScaleTheWorld.esp
    ComparisonValue: 1
- Text:
    TargetLanguage: English
    Value: Configure Active Scaling Preset
- Text:
    TargetLanguage: English
    Value: Configure Enabled Easter Eggs
