FormKey: 000804:ScaleTheWorldTheSequel.esm
EditorID: co_Inventory_ScaleTheWorldTheSequel_ConfigTerminal
Description:
  TargetLanguage: English
  Value: Scale the World - The Sequel Configuration Terminal
WorkbenchKeyword: 0AA209:Starfield.esm
Conditions:
- MutagenObjectType: ConditionFloat
  Unknown1: 0x000000
  Data:
    MutagenObjectType: GetItemCountConditionData
    RunOnType: Reference
    Reference: 000014:Starfield.esm
    FirstParameter: 000805:ScaleTheWorldTheSequel.esm
ConstructableComponents:
- Component: 0057C7:Starfield.esm
  Count: 1
CreatedObject: 000805:ScaleTheWorldTheSequel.esm
AmountProduced: 1
LearnMethod: DefaultOrConditions
Categories:
- 2E2F2D:Starfield.esm
RECF: 0
