FormKey: 000805:Venworks-ScaleTheWorld.esp
EditorID: STWTS_ConfigTerminal
Transforms:
  Inventory: 003000:Venworks-ScaleTheWorld.esp
Name:
  TargetLanguage: English
  Value: Scale the World Config Terminal
Keywords:
- 0F4AE7:Starfield.esm
- 11A47A:Starfield.esm
Model:
  File: SetDressing\Hackers_Laptop\hackers_laptop_01.nif
  FLLD: 0x01000000
PickupSound:
  Start: 3ab34823-87d6-d2c0-6fc0-21a73d163797
DropdownSound:
  Start: 6c474054-5b00-4ba2-302a-3ac846a9f190
CraftingSound:
  Start: 44ec43e3-b64d-b271-7871-a0812718b7b9
Description:
  TargetLanguage: English
  Value: Open Scale the World Config Menu
Value: 1
Flags:
- NoAutoCalc
ConsumeSound:
  Start: 364648af-30ee-3fdb-690e-972506498c9d
  Stop: 5f5543f6-a121-42ef-5745-c702ba94a4a3
Effects:
- BaseEffect: 000807:Venworks-ScaleTheWorld.esp
  Data: {}
