FormKey: 00085C:ScaleTheWorldTheSequel.esm
EditorID: STWTS_ConfigTerminal_ActivePreset
Description:
  TargetLanguage: English
  Value: When you change the preset you really should switch to a new NGP session, but you can also leave any visited plants for 24 hours for the cell reset.
Name:
  TargetLanguage: English
  Value: Scaling Preset Selection
Flags:
- MessageBox
BNAM: 4294967295
MenuButtons:
- Text:
    TargetLanguage: English
    Value: Return to previous menu
- Text:
    TargetLanguage: English
    Value: Set to story mode scaling
  Conditions:
  - MutagenObjectType: ConditionFloat
    CompareOperator: NotEqualTo
    Unknown1: 0x000000
    Data:
      MutagenObjectType: GetGlobalValueConditionData
      FirstParameter: 000870:ScaleTheWorldTheSequel.esm
- Text:
    TargetLanguage: English
    Value: Set to easy scaling
  Conditions:
  - MutagenObjectType: ConditionFloat
    CompareOperator: NotEqualTo
    Unknown1: 0x000000
    Data:
      MutagenObjectType: GetGlobalValueConditionData
      FirstParameter: 000870:ScaleTheWorldTheSequel.esm
    ComparisonValue: 1
- Text:
    TargetLanguage: English
    Value: Set to normal scaling
  Conditions:
  - MutagenObjectType: ConditionFloat
    CompareOperator: NotEqualTo
    Unknown1: 0x000000
    Data:
      MutagenObjectType: GetGlobalValueConditionData
      FirstParameter: 000870:ScaleTheWorldTheSequel.esm
    ComparisonValue: 2
- Text:
    TargetLanguage: English
    Value: Set to hard scaling
  Conditions:
  - MutagenObjectType: ConditionFloat
    CompareOperator: NotEqualTo
    Unknown1: 0x000000
    Data:
      MutagenObjectType: GetGlobalValueConditionData
      FirstParameter: 000870:ScaleTheWorldTheSequel.esm
    ComparisonValue: 3
- Text:
    TargetLanguage: English
    Value: Set to nightmare scaling
  Conditions:
  - MutagenObjectType: ConditionFloat
    CompareOperator: NotEqualTo
    Unknown1: 0x000000
    Data:
      MutagenObjectType: GetGlobalValueConditionData
      FirstParameter: 000870:ScaleTheWorldTheSequel.esm
    ComparisonValue: 4
- Text:
    TargetLanguage: English
    Value: Set to apocalypse scaling
  Conditions:
  - MutagenObjectType: ConditionFloat
    CompareOperator: NotEqualTo
    Unknown1: 0x000000
    Data:
      MutagenObjectType: GetGlobalValueConditionData
      FirstParameter: 000870:ScaleTheWorldTheSequel.esm
    ComparisonValue: 5
