FormKey: 000807:ScaleTheWorldTheSequel.esm
EditorID: STWTS_ConfigTerminal
VirtualMachineAdapter:
  Scripts:
  - Name: STWTS_ConfigTerminalScript
    Properties:
    - MutagenObjectType: ScriptObjectProperty
      Name: STWTS_ConfigTerminal
      Object: 000805:ScaleTheWorldTheSequel.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: PlayerRef
      Object: 000014:Starfield.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: STWTS_ConfigTerminal_MainMenu
      Object: 000808:ScaleTheWorldTheSequel.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: STWTS_EasterEggMode_Critter
      Object: 000844:ScaleTheWorldTheSequel.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: STWTS_ActivePreset
      Object: 000870:ScaleTheWorldTheSequel.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: STWTS_Enabled
      Object: 000806:ScaleTheWorldTheSequel.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: Venpi_DebugEnabled
      Object: 000800:VenpiCore.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: STWTS_ConfigTerminal_ActivePreset
      Object: 00085C:ScaleTheWorldTheSequel.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: STWTS_ConfigTerminal_ConfigureEasterEggs
      Object: 000863:ScaleTheWorldTheSequel.esm
    - MutagenObjectType: ScriptStringProperty
      Name: Venpi_ModName
      Data: ScaleTheWorldTheSequel
Archetype:
  MutagenObjectType: MagicEffectArchetype
  Type: Script
UnkownInt2: 3
CastType: FireAndForget
UnkownInt3: 1065353216
Flags:
- HideInUI
- Painless
- NoHitEffect
Unknown: 0x00000000000000000000000000000000000000000000
